server:
  port: 9200
spring:
  application:
    name: config-server
  cloud:
    config:
      uri: https://github.com/yanhuasanyue1015/spring-cloud.git
      server:
        git:
          search-paths: config/'{application}'
