server:
  port: 9202
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          search-paths: 'config/{application}'
          uri: https://github.com/yanhuasanyue1015/spring-cloud.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/