server:
  port: 9200
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          search-paths: 'config/{application}'
          uri: https://github.com/yanhuasanyue1015/spring-cloud.git
